FROM node:8.1.0-alpine

WORKDIR /usr/src/app
RUN apk add --no-cache --virtual .gyp \
        python \
        make \
        g++ \
    && npm install \
        node-sass \
    && apk del .gyp

EXPOSE 3000
CMD ["yarn", "run", "start"]