language: node_js
node_js:
  - "7"

sudo: enabled

before_script:
  - npm install -g yarn
  - npm install -g webpack
script:
  - cd client && yarn && webpack
  - cd ../server && yarn

cache:
  directories:
    - "client/node_modules"
    - "server/node_modules"
  yarn: true