
version: '2'
services:
    client:
        build:
            context: ./
            dockerfile: client.docker
        volumes:
            - ./client:/var/www:rw
        ports:
            - "80:3000"
        environment:
            - NODE_ENV=dev
        links:
            - server
        command: >
            sh -c '
                if test -d node_modules; 
                then 
                echo node_modules_exists ; 
                else 
                cp -a /tmp/node_modules /var/www; 
                fi && 
                npm install --dev && 
                node ./index.js
            '
    server:
        build:
            context: ./
            dockerfile: server.docker
        volumes:
            - ./server:/var/www
        ports:
            - "8080:8080"
    db:
        image: frodenas/mongodb
        environment:
            MONGODB_USERNAME: pooch
            MONGODB_PASSWORD: pooch
            MONGODB_DBNAME: free-pooch
        ports:
            - "27017:27017"